name: build
on: [push, pull_request]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install 32-Bit Compilation Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: Generate Dynamic Makefile and Build
        run: |
          # Use your native local Makefile framework directly
          make clean
          make
