name: build
on: [push, pull_request]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Dynamic Makefile and Build
        run: |
          gcc -m32 -ffreestanding -O2 -Wall -Wextra -c src/main.c -o src/main.o
          gcc -m32 -ffreestanding -O2 -Wall -Wextra -c src/mmu.c -o src/mmu.o
          gcc -m32 -ffreestanding -O2 -Wall -Wextra -c src/uart_driver.c -o src/uart_driver.o
          gcc -m32 -ffreestanding -O2 -Wall -Wextra -c src/vector_table.c -o src/vector_table.o
          ld -m elf_i386 -T src/linker.ld -o os-kernel.bin src/app_radio_telemetry.o src/app_stego_panic.o src/app_upgrade_layer.o src/linker_fallbacks.o src/main.o src/mmu.o src/uart_driver.o src/vector_table.o
